import { GAME_CONFIG } from "../config/gameConfig";
import { createPlayerState } from "../systems/playerController";
import { loadProgress } from "../systems/progressStorage";
import type { GameState } from "./types";

export function createInitialGameState(): GameState {
  return {
    phase: "idle",
    player: createPlayerState(),
    timeElapsed: 0,
    worldOffset: 0,
    terrainSegments: [],
    nextTerrainSegmentId: 0,
    terrainPatternIndex: 0,
    nextObstacleId: 0,
    score: 0,
    multiplier: 1,
    combo: 0,
    comboTimer: 0,
    nearMissTimer: 0,
    nearMissPoints: 0,
    progress: loadProgress(),
    overclockActive: false,
    overclockTimer: 0,
    overclockFlash: 0,
    overclockAudioArmed: false,
    tokens: [],
    nextTokenAt: GAME_CONFIG.overclock.graceDistance,
    nextTokenId: 0,
    focusMeter: 0,
    focusActive: false,
    focusHeld: false,
    pumpCooldown: 0,
    pumpLandingWindow: 0,
    pumpCrouchTimer: 0,
    patchCount: 0,
    patchTokens: [],
    nextPatchTokenAt: GAME_CONFIG.patchPulse.graceDistance,
    nextPatchTokenId: 0,
    shockwaves: [],
    nextShockwaveId: 0,
    scoreSurgeTokens: [],
    nextScoreSurgeTokenId: 0,
    scoreSurgeActive: false,
    scoreSurgeTimer: 0,
    scoreSurgeFlash: 0,
    energyRings: [],
    nextEnergyRingId: 0,
    routeFeedbackText: "",
    routeFeedbackTimer: 0,
    lastRiskSegmentId: null,
    audioEvents: [],
    audioMuted: false,
  };
}
